## Config

### Imports

In [1]:
import os
import math
import pandas as pd
import numpy as np
from datetime import datetime
from IPython.display import display

### loading data

In [2]:
data_path = os.path.join("data", "output", "projetos_lattes_1.csv")
df1 = pd.read_csv(data_path, sep=";", encoding='utf-8-sig')
print(df1.shape)
df1.head(3)

(30, 27)

,lattes_id,professor,ano_inicio,ano_conclusao,projeto,descricao,situacao,natureza,alunos_envolvidos,integrantes,...,edital_ou_chamada,coordenador,valor_financiamento,financiador,tipo_bolsa,area_pgcomp,topico_pesquisa,palavras_chave,cooperacao_internacional,resumo_executivo
0,92226104911153,Bruno Pereira dos Santos,2024,NaN,Sistemas Resilientes para Ambientes Inteligent...,Situação: Em andamento; Natureza: Pesquisa. Al...,Em andamento,Pesquisa,Graduação: (4) / Mestrado acadêmico: (2) / Dou...,Bruno Pereira dos Santos - Integrante / Paulo ...,...,NaN,Paulo H. L. Rettore,NaN,['Conselho Nacional de Desenvolvimento Científ...,NaN,Ciência de Dados e Banco de Dados,Sistemas Resilientes,"['Sistemas Resilientes', 'Qualidade de Dados',...",NaN,O projeto aborda a qualidade dos dados e a con...
1,92226104911153,Bruno Pereira dos Santos,2024,NaN,Projeto ARGUS,Descrição: O aumento exponencial no volume de ...,Em andamento,Pesquisa,NaN,Bruno Pereira dos Santos - Integrante / Maycon...,...,NaN,Gustavo Bittencourt Figueiredo,NaN,[],Produtividade,Redes de Computadores e Sistemas Distribuídos,Computação Quântica,"['Computação Quântica', 'Veículos Autônomos', ...",NaN,O projeto visa desenvolver um framework para a...
2,92226104911153,Bruno Pereira dos Santos,2023,NaN,Aprendizado de Máquina Federado para Internet ...,Descrição: Os ecossistemas de Internet das Coi...,Em andamento,Pesquisa,Mestrado acadêmico: (2) Doutorado: (2),Bruno Pereira dos Santos - Integrante / Heitor...,...,NaN,Heitor S Ramos,NaN,['Fundação de Amparo à Pesquisa do Estado de M...,Formação Acadêmica,Inteligência Artificial e Aprendizado de Máquina,Aprendizado Federado para Internet das Coisas,"['Aprendizado Federado', 'Internet das Coisas'...",NaN,O projeto investiga a extração de conhecimento...

In [5]:
data_path = os.path.join("data", "output", "projetos_lattes_2.csv")
df2 = pd.read_csv(data_path, sep=";", encoding='utf-8-sig')
print(df2.shape)
df2.head(3)

(102, 27)

,lattes_id,professor,ano_inicio,ano_conclusao,projeto,descricao,situacao,natureza,alunos_envolvidos,integrantes,...,edital_ou_chamada,coordenador,valor_financiamento,financiador,tipo_bolsa,area_pgcomp,topico_pesquisa,palavras_chave,cooperacao_internacional,resumo_executivo
0,5.821602e+13,Islame Felipe da Costa Fernandes,2023.0,NaN,[Edital CNPq/MCTI 10/2023 - UNIVERSAL] Meta-ap...,Descrição: O Brasil é o sexto maior produtor m...,Em andamento,Pesquisa,NaN,Islame Felipe da Costa Fernandes - Coordenador...,...,NaN,José Alberto Cuminato,NaN,['Fundação de Amparo à Pesquisa do Estado de S...,Formação Acadêmica,Ciência de Dados e Banco de Dados,Transferência de conhecimento matemático para ...,"['Matemática Aplicada', 'Transferência de Conh...",NaN,O projeto visa transferir conhecimento matemát...
1,4.430958e+15,Ivan do Carmo Machado,2024.0,NaN,Uma Investigação Empírica da Relação entre Ref...,Descrição: A temática de refatoração tem sido ...,Em andamento,Pesquisa,Mestrado acadêmico: (3) Doutorado: (4),Ivan do Carmo Machado - Coordenador / Carla Il...,...,NaN,Manoel Gomes De Mendonça Neto,NaN,['Fundação de Amparo à Pesquisa do Estado da B...,Formação Acadêmica,Ciência da Computação,Transformação Digital,"['Transformação Digital', 'Indústria 4.0', 'In...",NaN,O projeto visa promover a transformação digita...
2,4.430958e+15,Ivan do Carmo Machado,2024.0,NaN,Consolidação da Rede Internacional de Pesquisa...,Descrição: O objetivo do projeto é promover a ...,Em andamento,Pesquisa,Mestrado acadêmico: (26) Doutorado: (26),Ivan do Carmo Machado - Integrante / Climene L...,...,NaN,Rita Suzana Pitangueira Maciel,NaN,['Conselho Nacional de Desenvolvimento Científ...,Formação Acadêmica,Ciência de Dados e Banco de Dados,Recomendação de pares confiáveis em Ambientes ...,"['Recomendação de pares', 'Confiança interpess...",NaN,Este projeto investiga sistemas de recomendaçã...

In [6]:
data_path = os.path.join("data", "output", "projetos_lattes_3.csv")
df3 = pd.read_csv(data_path, sep=";", encoding='utf-8-sig')
print(df3.shape)
df3.head(3)

(50, 27)

,lattes_id,professor,ano_inicio,ano_conclusao,projeto,descricao,situacao,natureza,alunos_envolvidos,integrantes,...,edital_ou_chamada,coordenador,valor_financiamento,financiador,tipo_bolsa,area_pgcomp,topico_pesquisa,palavras_chave,cooperacao_internacional,resumo_executivo
0,92226104911153,Bruno Pereira dos Santos,2024,NaN,Sistemas Resilientes para Ambientes Inteligent...,Situação: Em andamento; Natureza: Pesquisa. Al...,Em andamento,Pesquisa,Graduação: (4) / Mestrado acadêmico: (2) / Dou...,Bruno Pereira dos Santos - Integrante / Paulo ...,...,NaN,Paulo H. L. Rettore,NaN,['Conselho Nacional de Desenvolvimento Científ...,NaN,Ciência de Dados e Banco de Dados,Sistemas Resilientes,"['Sistemas Resilientes', 'Qualidade de Dados',...",NaN,O projeto aborda a qualidade dos dados e a con...
1,92226104911153,Bruno Pereira dos Santos,2024,NaN,Projeto ARGUS,Descrição: O aumento exponencial no volume de ...,Em andamento,Pesquisa,NaN,Bruno Pereira dos Santos - Integrante / Maycon...,...,NaN,Gustavo Bittencourt Figueiredo,NaN,[],Produtividade,Redes de Computadores e Sistemas Distribuídos,Computação Quântica,"['Computação Quântica', 'Veículos Autônomos', ...",NaN,O projeto visa desenvolver um framework para a...
2,92226104911153,Bruno Pereira dos Santos,2023,NaN,Aprendizado de Máquina Federado para Internet ...,Descrição: Os ecossistemas de Internet das Coi...,Em andamento,Pesquisa,Mestrado acadêmico: (2) Doutorado: (2),Bruno Pereira dos Santos - Integrante / Heitor...,...,NaN,Heitor S Ramos,NaN,['Fundação de Amparo à Pesquisa do Estado de M...,Formação Acadêmica,Inteligência Artificial e Aprendizado de Máquina,Aprendizado Federado para Internet das Coisas,"['Aprendizado Federado', 'Internet das Coisas'...",NaN,O projeto investiga a extração de conhecimento...

In [7]:
df = pd.concat([
    df1, df2, df3
])
print(df.shape)
df.head(3)

(182, 27)

,lattes_id,professor,ano_inicio,ano_conclusao,projeto,descricao,situacao,natureza,alunos_envolvidos,integrantes,...,edital_ou_chamada,coordenador,valor_financiamento,financiador,tipo_bolsa,area_pgcomp,topico_pesquisa,palavras_chave,cooperacao_internacional,resumo_executivo
0,9.222610e+13,Bruno Pereira dos Santos,2024.0,NaN,Sistemas Resilientes para Ambientes Inteligent...,Situação: Em andamento; Natureza: Pesquisa. Al...,Em andamento,Pesquisa,Graduação: (4) / Mestrado acadêmico: (2) / Dou...,Bruno Pereira dos Santos - Integrante / Paulo ...,...,NaN,Paulo H. L. Rettore,NaN,['Conselho Nacional de Desenvolvimento Científ...,NaN,Ciência de Dados e Banco de Dados,Sistemas Resilientes,"['Sistemas Resilientes', 'Qualidade de Dados',...",NaN,O projeto aborda a qualidade dos dados e a con...
1,9.222610e+13,Bruno Pereira dos Santos,2024.0,NaN,Projeto ARGUS,Descrição: O aumento exponencial no volume de ...,Em andamento,Pesquisa,NaN,Bruno Pereira dos Santos - Integrante / Maycon...,...,NaN,Gustavo Bittencourt Figueiredo,NaN,[],Produtividade,Redes de Computadores e Sistemas Distribuídos,Computação Quântica,"['Computação Quântica', 'Veículos Autônomos', ...",NaN,O projeto visa desenvolver um framework para a...
2,9.222610e+13,Bruno Pereira dos Santos,2023.0,NaN,Aprendizado de Máquina Federado para Internet ...,Descrição: Os ecossistemas de Internet das Coi...,Em andamento,Pesquisa,Mestrado acadêmico: (2) Doutorado: (2),Bruno Pereira dos Santos - Integrante / Heitor...,...,NaN,Heitor S Ramos,NaN,['Fundação de Amparo à Pesquisa do Estado de M...,Formação Acadêmica,Inteligência Artificial e Aprendizado de Máquina,Aprendizado Federado para Internet das Coisas,"['Aprendizado Federado', 'Internet das Coisas'...",NaN,O projeto investiga a extração de conhecimento...

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 182 entries, 0 to 49
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lattes_id                 153 non-null    float64
 1   professor                 153 non-null    str
 2   ano_inicio                153 non-null    float64
 3   ano_conclusao             51 non-null     float64
 4   projeto                   153 non-null    str
 5   descricao                 153 non-null    str
 6   situacao                  153 non-null    str
 7   natureza                  153 non-null    str
 8   alunos_envolvidos         97 non-null     str
 9   integrantes               153 non-null    str
 10  financiadores             74 non-null     str
 11  descricao_limpa           153 non-null    str
 12  edital                    24 non-null     str
 13  qtd_graduacao             153 non-null    float64
 14  qtd_mestrado              153 non-null    float64
 15  qtd_doutorado             153 non-null    float64
 16  total_alunos              153 non-null    float64
 17  edital_ou_chamada         52 non-null     str
 18  coordenador               153 non-null    str
 19  valor_financiamento       17 non-null     str
 20  financiador               153 non-null    str
 21  tipo_bolsa                107 non-null    str
 22  area_pgcomp               153 non-null    str
 23  topico_pesquisa           153 non-null    str
 24  palavras_chave            153 non-null    str
 25  cooperacao_internacional  14 non-null     object
 26  resumo_executivo          149 non-null    str
dtypes: float64(7), object(1), str(19)
memory usage: 39.8+ KB

In [9]:
df.isna().sum()

lattes_id                    29
professor                    29
ano_inicio                   29
ano_conclusao               131
projeto                      29
descricao                    29
situacao                     29
natureza                     29
alunos_envolvidos            85
integrantes                  29
financiadores               108
descricao_limpa              29
edital                      158
qtd_graduacao                29
qtd_mestrado                 29
qtd_doutorado                29
total_alunos                 29
edital_ou_chamada           130
coordenador                  29
valor_financiamento         165
financiador                  29
tipo_bolsa                   75
area_pgcomp                  29
topico_pesquisa              29
palavras_chave               29
cooperacao_internacional    168
resumo_executivo             33
dtype: int64

In [9]:
df2.isna().sum()

lattes_id                   29
professor                   29
ano_inicio                  29
ano_conclusao               75
projeto                     29
descricao                   29
situacao                    29
natureza                    29
alunos_envolvidos           54
integrantes                 29
financiadores               61
descricao_limpa             29
edital                      91
qtd_graduacao               29
qtd_mestrado                29
qtd_doutorado               29
total_alunos                29
edital_ou_chamada           75
coordenador                 29
valor_financiamento         94
financiador                 29
tipo_bolsa                  46
area_pgcomp                 29
topico_pesquisa             29
palavras_chave              29
cooperacao_internacional    93
resumo_executivo            32
dtype: int64

In [15]:
df_ = df.loc[~df["lattes_id"].isna()]
df_.shape

(153, 27)

In [16]:
df_["lattes_id"].isna().sum()

np.int64(0)

## Processing

### Formatting types

In [17]:
df_["ano_conclusao"] = df_["ano_conclusao"].astype("Int64")
df_.info()

<class 'pandas.DataFrame'>
Index: 153 entries, 0 to 49
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lattes_id                 153 non-null    float64
 1   professor                 153 non-null    str
 2   ano_inicio                153 non-null    float64
 3   ano_conclusao             51 non-null     Int64
 4   projeto                   153 non-null    str
 5   descricao                 153 non-null    str
 6   situacao                  153 non-null    str
 7   natureza                  153 non-null    str
 8   alunos_envolvidos         97 non-null     str
 9   integrantes               153 non-null    str
 10  financiadores             74 non-null     str
 11  descricao_limpa           153 non-null    str
 12  edital                    24 non-null     str
 13  qtd_graduacao             153 non-null    float64
 14  qtd_mestrado              153 non-null    float64
 15  qtd_doutorado             153 non-null    float64
 16  total_alunos              153 non-null    float64
 17  edital_ou_chamada         41 non-null     str
 18  coordenador               124 non-null    str
 19  valor_financiamento       14 non-null     str
 20  financiador               124 non-null    str
 21  tipo_bolsa                84 non-null     str
 22  area_pgcomp               124 non-null    str
 23  topico_pesquisa           124 non-null    str
 24  palavras_chave            124 non-null    str
 25  cooperacao_internacional  11 non-null     object
 26  resumo_executivo          121 non-null    str
dtypes: Int64(1), float64(6), object(1), str(19)
memory usage: 33.6+ KB

### Saving

In [18]:
df_.to_csv(os.path.join("data", "output", "processed_projetos_2025_2026.csv"), sep=";", encoding='utf-8-sig', index=False)