## Config

### Imports

In [1]:
import os
import math
import pandas as pd
import numpy as np
from datetime import datetime
from IPython.display import display

### loading data

In [2]:
data_path = os.path.join("data", "output", "projetos_lattes_completo.csv")
df = pd.read_csv(data_path, sep=";", encoding='utf-8-sig')
print(df.shape)
df.head()

(171, 24)

,lattes_id,professor,ano_inicio,ano_conclusao,projeto,descricao,situacao,natureza,alunos_envolvidos,integrantes,...,qtd_doutorado,total_alunos,edital_ou_chamada,coordenador,financiador,area_pgcomp,topico_pesquisa,palavras_chave,cooperacao_internacional,resumo_executivo
0,4430958315746203,Ivan do Carmo Machado,2024,NaN,Uma Investigação Empírica da Relação entre Ref...,Descrição: A temática de refatoração tem sido ...,Em andamento,Pesquisa,Mestrado acadêmico: (3) Doutorado: (4),Ivan do Carmo Machado - Coordenador / Carla Il...,...,4,7,Situação: Em andamento; Natureza: Pesquisa,Ivan do Carmo Machado,['Conselho Nacional de Desenvolvimento Científ...,Visualização de Dados e Processamento de Imagens,Refatoração de Testes,"['refatoração', 'teste de software', 'qualidad...",False,Este projeto investigará a refatoração de test...
1,4430958315746203,Ivan do Carmo Machado,2024,NaN,Consolidação da Rede Internacional de Pesquisa...,Descrição: O objetivo do projeto é promover a ...,Em andamento,Pesquisa,Mestrado acadêmico: (26) Doutorado: (26),Ivan do Carmo Machado - Integrante / Climene L...,...,26,52,Em andamento,Climene Laura de Camargo,['Universidade Portuguesa'],Outra,Formação Acadêmica de Negros e Indígenas,"['Formação Acadêmica', 'Negros', 'Indígenas', ...",True,Promover a formação acadêmica de negros e indí...
2,4430958315746203,Ivan do Carmo Machado,2023,NaN,Melhoria da Qualidade de Software na Perspecti...,Descrição: O projeto vista investigar test sme...,Em andamento,Pesquisa,Graduação: (2) / Mestrado acadêmico: (2) / Dou...,Ivan do Carmo Machado - Integrante / rohit Ghe...,...,6,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4430958315746203,Ivan do Carmo Machado,2023,NaN,"SI2 - Instituto de Ciência, Tecnologia e Inova...",Descrição: Este projeto tem como objetivo gera...,Em andamento,Pesquisa,NaN,Ivan do Carmo Machado - Integrante / Eduardo S...,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4430958315746203,Ivan do Carmo Machado,2023,NaN,ALICE: Uma infrAestrutura para meLhoria da qua...,Descrição: Este projeto propõe a construção de...,Em andamento,Pesquisa,Graduação: (2) / Doutorado: (3),Ivan do Carmo Machado - Coordenador / Larissa ...,...,3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lattes_id                 171 non-null    int64
 1   professor                 171 non-null    str
 2   ano_inicio                171 non-null    int64
 3   ano_conclusao             126 non-null    float64
 4   projeto                   171 non-null    str
 5   descricao                 171 non-null    str
 6   situacao                  171 non-null    str
 7   natureza                  171 non-null    str
 8   alunos_envolvidos         121 non-null    str
 9   integrantes               171 non-null    str
 10  financiadores             107 non-null    str
 11  descricao_limpa           171 non-null    str
 12  qtd_graduacao             171 non-null    int64
 13  qtd_mestrado              171 non-null    int64
 14  qtd_doutorado             171 non-null    int64
 15  total_alunos              171 non-null    int64
 16  edital_ou_chamada         51 non-null     str
 17  coordenador               54 non-null     str
 18  financiador               53 non-null     str
 19  area_pgcomp               54 non-null     str
 20  topico_pesquisa           54 non-null     str
 21  palavras_chave            54 non-null     str
 22  cooperacao_internacional  54 non-null     object
 23  resumo_executivo          54 non-null     str
dtypes: float64(1), int64(6), object(1), str(16)
memory usage: 32.2+ KB

In [4]:
df.isna().sum()

lattes_id                     0
professor                     0
ano_inicio                    0
ano_conclusao                45
projeto                       0
descricao                     0
situacao                      0
natureza                      0
alunos_envolvidos            50
integrantes                   0
financiadores                64
descricao_limpa               0
qtd_graduacao                 0
qtd_mestrado                  0
qtd_doutorado                 0
total_alunos                  0
edital_ou_chamada           120
coordenador                 117
financiador                 118
area_pgcomp                 117
topico_pesquisa             117
palavras_chave              117
cooperacao_internacional    117
resumo_executivo            117
dtype: int64

## Processing

### Formatting types

In [5]:
df["ano_conclusao"] = df["ano_conclusao"].astype("Int64")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lattes_id                 171 non-null    int64
 1   professor                 171 non-null    str
 2   ano_inicio                171 non-null    int64
 3   ano_conclusao             126 non-null    Int64
 4   projeto                   171 non-null    str
 5   descricao                 171 non-null    str
 6   situacao                  171 non-null    str
 7   natureza                  171 non-null    str
 8   alunos_envolvidos         121 non-null    str
 9   integrantes               171 non-null    str
 10  financiadores             107 non-null    str
 11  descricao_limpa           171 non-null    str
 12  qtd_graduacao             171 non-null    int64
 13  qtd_mestrado              171 non-null    int64
 14  qtd_doutorado             171 non-null    int64
 15  total_alunos              171 non-null    int64
 16  edital_ou_chamada         51 non-null     str
 17  coordenador               54 non-null     str
 18  financiador               53 non-null     str
 19  area_pgcomp               54 non-null     str
 20  topico_pesquisa           54 non-null     str
 21  palavras_chave            54 non-null     str
 22  cooperacao_internacional  54 non-null     object
 23  resumo_executivo          54 non-null     str
dtypes: Int64(1), int64(6), object(1), str(16)
memory usage: 32.4+ KB

### Extracting 2025 projects

In [6]:
columns = df.columns.tolist()
print(columns)

['lattes_id', 'professor', 'ano_inicio', 'ano_conclusao', 'projeto', 'descricao', 'situacao', 'natureza', 'alunos_envolvidos', 'integrantes', 'financiadores', 'descricao_limpa', 'qtd_graduacao', 'qtd_mestrado', 'qtd_doutorado', 'total_alunos', 'edital_ou_chamada', 'coordenador', 'financiador', 'area_pgcomp', 'topico_pesquisa', 'palavras_chave', 'cooperacao_internacional', 'resumo_executivo']

In [7]:
df["ano_inicio"].unique()

array([2024, 2023, 2020, 2019, 2018, 2017, 2012, 2011, 2010, 2022, 2015,
       2014, 2002, 2013, 2007, 2006, 2004, 2021, 2009, 2005, 2001, 2000,
       2016, 2008])

In [8]:
df["ano_conclusao"].unique()

<IntegerArray>
[<NA>, 2024, 2022, 2014, 2013, 2012, 2025, 2020, 2018, 2004, 2021, 2016, 2015,
 2010, 2008, 2006, 2019, 2002, 2017, 2023, 2026]
Length: 21, dtype: Int64

projetos que nao possuem valor em ano de conclusao significam que ainda estao rodando

In [9]:
current = df.loc[df["ano_conclusao"].isna()]
print(f"{current.shape}\n")
current.head()

(45, 24)

,lattes_id,professor,ano_inicio,ano_conclusao,projeto,descricao,situacao,natureza,alunos_envolvidos,integrantes,...,qtd_doutorado,total_alunos,edital_ou_chamada,coordenador,financiador,area_pgcomp,topico_pesquisa,palavras_chave,cooperacao_internacional,resumo_executivo
0,4430958315746203,Ivan do Carmo Machado,2024,<NA>,Uma Investigação Empírica da Relação entre Ref...,Descrição: A temática de refatoração tem sido ...,Em andamento,Pesquisa,Mestrado acadêmico: (3) Doutorado: (4),Ivan do Carmo Machado - Coordenador / Carla Il...,...,4,7,Situação: Em andamento; Natureza: Pesquisa,Ivan do Carmo Machado,['Conselho Nacional de Desenvolvimento Científ...,Visualização de Dados e Processamento de Imagens,Refatoração de Testes,"['refatoração', 'teste de software', 'qualidad...",False,Este projeto investigará a refatoração de test...
1,4430958315746203,Ivan do Carmo Machado,2024,<NA>,Consolidação da Rede Internacional de Pesquisa...,Descrição: O objetivo do projeto é promover a ...,Em andamento,Pesquisa,Mestrado acadêmico: (26) Doutorado: (26),Ivan do Carmo Machado - Integrante / Climene L...,...,26,52,Em andamento,Climene Laura de Camargo,['Universidade Portuguesa'],Outra,Formação Acadêmica de Negros e Indígenas,"['Formação Acadêmica', 'Negros', 'Indígenas', ...",True,Promover a formação acadêmica de negros e indí...
2,4430958315746203,Ivan do Carmo Machado,2023,<NA>,Melhoria da Qualidade de Software na Perspecti...,Descrição: O projeto vista investigar test sme...,Em andamento,Pesquisa,Graduação: (2) / Mestrado acadêmico: (2) / Dou...,Ivan do Carmo Machado - Integrante / rohit Ghe...,...,6,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4430958315746203,Ivan do Carmo Machado,2023,<NA>,"SI2 - Instituto de Ciência, Tecnologia e Inova...",Descrição: Este projeto tem como objetivo gera...,Em andamento,Pesquisa,NaN,Ivan do Carmo Machado - Integrante / Eduardo S...,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4430958315746203,Ivan do Carmo Machado,2023,<NA>,ALICE: Uma infrAestrutura para meLhoria da qua...,Descrição: Este projeto propõe a construção de...,Em andamento,Pesquisa,Graduação: (2) / Doutorado: (3),Ivan do Carmo Machado - Coordenador / Larissa ...,...,3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
current["situacao"].unique()

<StringArray>
['Em andamento']
Length: 1, dtype: str

#### 2026

In [11]:
df["ano_inicio"].unique()

array([2024, 2023, 2020, 2019, 2018, 2017, 2012, 2011, 2010, 2022, 2015,
       2014, 2002, 2013, 2007, 2006, 2004, 2021, 2009, 2005, 2001, 2000,
       2016, 2008])

In [12]:
on_going_df = df.loc[df["ano_inicio"] == 2026]
print(f"{on_going_df.shape}\n")
on_going_df.head()

(0, 24)

Empty DataFrame
Columns: [lattes_id, professor, ano_inicio, ano_conclusao, projeto, descricao, situacao, natureza, alunos_envolvidos, integrantes, financiadores, descricao_limpa, qtd_graduacao, qtd_mestrado, qtd_doutorado, total_alunos, edital_ou_chamada, coordenador, financiador, area_pgcomp, topico_pesquisa, palavras_chave, cooperacao_internacional, resumo_executivo]
Index: []

[0 rows x 24 columns]

In [13]:
finished_this_year = df.loc[df["ano_conclusao"] == 2026]
print(f"{finished_this_year.shape}\n")
finished_this_year.head()

(2, 24)

,lattes_id,professor,ano_inicio,ano_conclusao,projeto,descricao,situacao,natureza,alunos_envolvidos,integrantes,...,qtd_doutorado,total_alunos,edital_ou_chamada,coordenador,financiador,area_pgcomp,topico_pesquisa,palavras_chave,cooperacao_internacional,resumo_executivo
109,427387583450747,Ricardo Araújo Rios,2023,2026,Sistema inteligente para estimar a carga de pa...,Descrição: O projeto visa desenvolver um siste...,Concluído,Pesquisa,Graduação: (2) / Mestrado acadêmico: (1),Ricardo Araújo Rios - Coordenador,...,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,427387583450747,Ricardo Araújo Rios,2023,2026,Rede de Referência de Inteligência Artificial ...,Descrição: O projeto tem por objeto a Dissemin...,Concluído,Pesquisa,NaN,Ricardo Araújo Rios - Integrante / Tatiane Mar...,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
this_year_df = pd.concat([
    current,
    on_going_df,
    finished_this_year
])
print(f"{this_year_df.shape}\n")
this_year_df.head()

(47, 24)

,lattes_id,professor,ano_inicio,ano_conclusao,projeto,descricao,situacao,natureza,alunos_envolvidos,integrantes,...,qtd_doutorado,total_alunos,edital_ou_chamada,coordenador,financiador,area_pgcomp,topico_pesquisa,palavras_chave,cooperacao_internacional,resumo_executivo
0,4430958315746203,Ivan do Carmo Machado,2024,<NA>,Uma Investigação Empírica da Relação entre Ref...,Descrição: A temática de refatoração tem sido ...,Em andamento,Pesquisa,Mestrado acadêmico: (3) Doutorado: (4),Ivan do Carmo Machado - Coordenador / Carla Il...,...,4,7,Situação: Em andamento; Natureza: Pesquisa,Ivan do Carmo Machado,['Conselho Nacional de Desenvolvimento Científ...,Visualização de Dados e Processamento de Imagens,Refatoração de Testes,"['refatoração', 'teste de software', 'qualidad...",False,Este projeto investigará a refatoração de test...
1,4430958315746203,Ivan do Carmo Machado,2024,<NA>,Consolidação da Rede Internacional de Pesquisa...,Descrição: O objetivo do projeto é promover a ...,Em andamento,Pesquisa,Mestrado acadêmico: (26) Doutorado: (26),Ivan do Carmo Machado - Integrante / Climene L...,...,26,52,Em andamento,Climene Laura de Camargo,['Universidade Portuguesa'],Outra,Formação Acadêmica de Negros e Indígenas,"['Formação Acadêmica', 'Negros', 'Indígenas', ...",True,Promover a formação acadêmica de negros e indí...
2,4430958315746203,Ivan do Carmo Machado,2023,<NA>,Melhoria da Qualidade de Software na Perspecti...,Descrição: O projeto vista investigar test sme...,Em andamento,Pesquisa,Graduação: (2) / Mestrado acadêmico: (2) / Dou...,Ivan do Carmo Machado - Integrante / rohit Ghe...,...,6,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4430958315746203,Ivan do Carmo Machado,2023,<NA>,"SI2 - Instituto de Ciência, Tecnologia e Inova...",Descrição: Este projeto tem como objetivo gera...,Em andamento,Pesquisa,NaN,Ivan do Carmo Machado - Integrante / Eduardo S...,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4430958315746203,Ivan do Carmo Machado,2023,<NA>,ALICE: Uma infrAestrutura para meLhoria da qua...,Descrição: Este projeto propõe a construção de...,Em andamento,Pesquisa,Graduação: (2) / Doutorado: (3),Ivan do Carmo Machado - Coordenador / Larissa ...,...,3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 2025

pegando apenas projetos que estiveram em execucao durante 2025 -> isso significa que projetos iniciados ANTES de 2026 e FINALIZADOS ou NAO em 2025

In [15]:
# concluidos em 2025
fb = df.loc[df["ano_conclusao"] == 2025]
print(f"{fb.shape}\n")
fb.head()

(6, 24)

,lattes_id,professor,ano_inicio,ano_conclusao,projeto,descricao,situacao,natureza,alunos_envolvidos,integrantes,...,qtd_doutorado,total_alunos,edital_ou_chamada,coordenador,financiador,area_pgcomp,topico_pesquisa,palavras_chave,cooperacao_internacional,resumo_executivo
15,1952937182023132,Leobino Nascimento Sampaio,2022,2025,Humanos no Ciclo da Comunicação Através das Re...,Descrição: Este projeto investiga como explora...,Concluído,Pesquisa,Graduação: (2) / Mestrado acadêmico: (2) / Dou...,Leobino Nascimento Sampaio - Coordenador.,...,6,10,Conclusão,Leobino Nascimento Sampaio,[],Redes de Computadores e Sistemas Distribuídos,Arquitetura NDN,"['NDN', 'Computação de Borda', 'Aplicações Dis...",False,Este projeto investiga a aplicabilidade da Arq...
16,1952937182023132,Leobino Nascimento Sampaio,2022,2025,Redes de Dados Nomeados e Internet das Coisas ...,Descrição: Dentre as propostas de novas arquit...,Concluído,Pesquisa,Graduação: (1) / Mestrado acadêmico: (1) / Dou...,Leobino Nascimento Sampaio - Coordenador / Adr...,...,2,4,Conclusão,Leobino Nascimento Sampaio,['NDN'],Redes de Computadores e Sistemas Distribuídos,Arquitetura NDN e IoT para Aplicações Ambient ...,"['NDN', 'IoT', 'Aplicação Ambient Assistida']",False,Investiga-se a aplicabilidade da arquitetura N...
49,1608062196337851,Manoel Gomes de Mendonça Neto,2019,2025,UAware: Uma Plataforma de Comunicação de Crise...,"Descrição: m cidades inteligentes, é important...",Concluído,Pesquisa,Graduação: (1) / Mestrado acadêmico: (5) / Dou...,Manoel Gomes de Mendonça Neto - Integrante / L...,...,1,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,5003713680310544,Maycon Leone Maciel Peixoto,2024,2025,Computação Quântica aplicada na Análise de Dad...,Descrição: Nas redes veiculares VANETs (Vehicu...,Concluído,Pesquisa,NaN,Maycon Leone Maciel Peixoto - Coordenador.,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,5003713680310544,Maycon Leone Maciel Peixoto,2024,2025,Projeto ARGUS,"Descrição: No cenário atual, a segurança patri...",Concluído,Pesquisa,NaN,Maycon Leone Maciel Peixoto - Coordenador.,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# em andamento em 2025
og = current.loc[current["ano_inicio"] < 2026]
print(f"{og.shape}\n")
og.head()

(45, 24)

,lattes_id,professor,ano_inicio,ano_conclusao,projeto,descricao,situacao,natureza,alunos_envolvidos,integrantes,...,qtd_doutorado,total_alunos,edital_ou_chamada,coordenador,financiador,area_pgcomp,topico_pesquisa,palavras_chave,cooperacao_internacional,resumo_executivo
0,4430958315746203,Ivan do Carmo Machado,2024,<NA>,Uma Investigação Empírica da Relação entre Ref...,Descrição: A temática de refatoração tem sido ...,Em andamento,Pesquisa,Mestrado acadêmico: (3) Doutorado: (4),Ivan do Carmo Machado - Coordenador / Carla Il...,...,4,7,Situação: Em andamento; Natureza: Pesquisa,Ivan do Carmo Machado,['Conselho Nacional de Desenvolvimento Científ...,Visualização de Dados e Processamento de Imagens,Refatoração de Testes,"['refatoração', 'teste de software', 'qualidad...",False,Este projeto investigará a refatoração de test...
1,4430958315746203,Ivan do Carmo Machado,2024,<NA>,Consolidação da Rede Internacional de Pesquisa...,Descrição: O objetivo do projeto é promover a ...,Em andamento,Pesquisa,Mestrado acadêmico: (26) Doutorado: (26),Ivan do Carmo Machado - Integrante / Climene L...,...,26,52,Em andamento,Climene Laura de Camargo,['Universidade Portuguesa'],Outra,Formação Acadêmica de Negros e Indígenas,"['Formação Acadêmica', 'Negros', 'Indígenas', ...",True,Promover a formação acadêmica de negros e indí...
2,4430958315746203,Ivan do Carmo Machado,2023,<NA>,Melhoria da Qualidade de Software na Perspecti...,Descrição: O projeto vista investigar test sme...,Em andamento,Pesquisa,Graduação: (2) / Mestrado acadêmico: (2) / Dou...,Ivan do Carmo Machado - Integrante / rohit Ghe...,...,6,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4430958315746203,Ivan do Carmo Machado,2023,<NA>,"SI2 - Instituto de Ciência, Tecnologia e Inova...",Descrição: Este projeto tem como objetivo gera...,Em andamento,Pesquisa,NaN,Ivan do Carmo Machado - Integrante / Eduardo S...,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4430958315746203,Ivan do Carmo Machado,2023,<NA>,ALICE: Uma infrAestrutura para meLhoria da qua...,Descrição: Este projeto propõe a construção de...,Em andamento,Pesquisa,Graduação: (2) / Doutorado: (3),Ivan do Carmo Machado - Coordenador / Larissa ...,...,3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
last_year_df = pd.concat([
    finished_this_year,
    fb,
    og 
])
print(f"{last_year_df.shape}\n")
last_year_df.head(3)

(53, 24)

,lattes_id,professor,ano_inicio,ano_conclusao,projeto,descricao,situacao,natureza,alunos_envolvidos,integrantes,...,qtd_doutorado,total_alunos,edital_ou_chamada,coordenador,financiador,area_pgcomp,topico_pesquisa,palavras_chave,cooperacao_internacional,resumo_executivo
109,427387583450747,Ricardo Araújo Rios,2023,2026,Sistema inteligente para estimar a carga de pa...,Descrição: O projeto visa desenvolver um siste...,Concluído,Pesquisa,Graduação: (2) / Mestrado acadêmico: (1),Ricardo Araújo Rios - Coordenador,...,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,427387583450747,Ricardo Araújo Rios,2023,2026,Rede de Referência de Inteligência Artificial ...,Descrição: O projeto tem por objeto a Dissemin...,Concluído,Pesquisa,NaN,Ricardo Araújo Rios - Integrante / Tatiane Mar...,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1952937182023132,Leobino Nascimento Sampaio,2022,2025,Humanos no Ciclo da Comunicação Através das Re...,Descrição: Este projeto investiga como explora...,Concluído,Pesquisa,Graduação: (2) / Mestrado acadêmico: (2) / Dou...,Leobino Nascimento Sampaio - Coordenador.,...,6,10,Conclusão,Leobino Nascimento Sampaio,[],Redes de Computadores e Sistemas Distribuídos,Arquitetura NDN,"['NDN', 'Computação de Borda', 'Aplicações Dis...",False,Este projeto investiga a aplicabilidade da Arq...

In [18]:
last_year_df["ano_inicio"].unique()

array([2023, 2022, 2019, 2024, 2015, 2018, 2013, 2017, 2016, 2021, 2020])

In [19]:
last_year_df["ano_conclusao"].unique()

<IntegerArray>
[2026, 2025, <NA>]
Length: 3, dtype: Int64

### Saving

In [20]:
# both
both_df = pd.concat([
    this_year_df,
    last_year_df
]).drop_duplicates().reset_index(drop=True)
print(f"{both_df.shape}\n")
both_df.to_csv(os.path.join("data", "output", "projetos_2025_2026.csv"), sep=";", encoding='utf-8-sig', index=False)

(53, 24)

In [21]:
this_year_df.to_csv(os.path.join("data", "output", "projetos_2026.csv"), sep=";", encoding='utf-8-sig', index=False)
last_year_df.to_csv(os.path.join("data", "output", "projetos_2025.csv"), sep=";", encoding='utf-8-sig', index=False)